apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-pg-credentials
  namespace: automation-orchestrator
type: Opaque
stringData:
  database: "orchestrator"
  username: "orchestrator"
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-pg-credentials
  namespace: automation-orchestrator
type: Opaque
stringData:
  database: "temporal"
  username: "temporal"
  password: ""
