apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
 name: udn-primary
 namespace: udn-vms
spec:
 topology: Layer2
 layer2:
   role: Primary
   subnets: 
   - 10.250.200.0/24
   ipam: 
     lifecycle: Persistent
